# Generated by Django 3.2.9 on 2022-05-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertech',
            name='perfilFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.perfil'),
        ),
    ]
